export const assets = [{url:"clampy.png",name:"clampy"},
                        {url:"Nave.png",name:"Nave"},
                        //Fuego
                        {url:"Fuego/Fuego2.png",name:"Fuego2"},
                        {url:"Fuego/Fuego3.png",name:"Fuego3"},
                        {url:"Fuego/Fuego1.png",name:"Fuego1"},
                        {url:"Fuego/Fuego4.png",name:"Fuego4"},
                        {url:"Fuego/Fuego5.png",name:"Fuego5"},
                        {url:"Fuego/Fuego6.png",name:"Fuego6"},
                        {url:"Espacio.jpg",name:"Espacio"},
                        {url:"Fondo.png",name:"Fondo"},
                        //Reiniciar
                        {url:"Retry/Retry.png",name:"Retry"},
                        {url:"Retry/Retry1.png",name:"Retry1"},
                        {url:"Retry/Retry2.png",name:"Retry2"},
                        {url:"Retry/Retry3.png",name:"Retry3"},
                        {url:"Retry/Retry4.png",name:"Retry4"},
                        {url:"Retry/Retry5.png",name:"Retry5"},
                        {url:"Retry/Retry6.png",name:"Retry6"},
                        {url:"Retry/Retry7.png",name:"Retry7"},
                        {url:"Retry/Retry8.png",name:"Retry8"},
                        {url:"Retry/Retry9.png",name:"Retry9"},
                        {url:"Retry/Retry10.png",name:"Retry10"},
                        //Configuracion
                        {url:"Configuracion/Configuracion.png",name:"Config"},
                        {url:"Configuracion/Configuracion1.png",name:"Config1"},
                        {url:"Configuracion/Configuracion2.png",name:"Config2"},
                        //Cerrar
                        {url:"Cerrar/Cerrar.png",name:"Cerrar"},
                        {url:"Cerrar/Cerrar1.png",name:"Cerrar1"},
                        {url:"Cerrar/Cerrar2.png",name:"Cerrar2"},
                        {url:"Estrella.png",name:"Estrella"},
                        //Fondo y Sol y Luna(plataforma)
                        {url:"Fondo/FondoNoche.jpg",name:"FondoNoche"},
                        {url:"Fondo/FondoSoleado.jpg",name:"FondoSoleado"},
                        {url:"Fondo/Sol.png",name:"Sol"},
                        {url:"Fondo/Luna.png",name:"Luna"},

                        //sonido
                        {url:"Musica/darkcat-MAPLEADVENTURE.mp3",name:"DarkCat"}
                    ];